server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123456
  application:
    name: service-provider  #将来作为微服务的名称

mybatis:
  type-aliases-package: com.legend.service.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: true