server:
  port: 8011
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 5

service-provider: #服务提供方的服务id
  ribbon:
    #指定自定义的负载均衡策略的类(全路径)
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule