# 服务端口号
server:
  port: 8011


# 微服务名称
spring:
  application:
    name: service-consumer

# eureka客户端相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 5

service-provider: #服务提供方的服务id
  ribbon:
    #指定自定义的负载均衡策略的类(全路径)
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#生产环境需要设置长一定超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #设置Hystrix的超时时间为6000ms


# Spring Cloud Feign 支持对请求和响应进行GZIP压缩，以减少通信过程中的性能损耗
feign:
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩