#主从数据库配置
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://localhost:3308/test_master?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    slave2:
      jdbc-url: jdbc:mysql://localhost:3308/test_master?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver