server:
  port: 9090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0
        max-active: 8
  application:
    name: accesslog

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
