spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M


# MinIO对象存储相关配置
minio:
  endpoint: http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: test-minio #存储桶名称
  accessKey: EIKDDECHC3X95UKHCUW7 #访问的key
  secretKey: DR+w+Paz5UpaQMwecrFyxJCQRXNGbWCATfxTxTfg #访问的秘钥