server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false


# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      capital-mode: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.qcl.mybatisplus
  configuration:
    map-underscore-to-camel-case: true


